package export

import "core:fmt"
import "core:strings"

import "src:trace/codec"

// HTML report rendering.
//
// docs/08-security.md: HTML output uses a fixed template with escaped text, a
// restrictive content security policy, no remote resources, and no executable
// JavaScript requirement.
//
// Every one of those is a property of this file rather than of a library:
// the template is a literal here, all text goes through escape_html, the CSP
// is emitted first, styling is inline, and there is no script element at all.
// A report that needed JavaScript to be readable would also be a report that
// could execute trace content.

// CSP is the policy embedded in every report.
//
// `default-src 'none'` denies everything and the two additions re-permit only
// what a static document needs. Notably absent: `script-src`, so no script can
// run even if one were somehow injected, and any `img-src`, so a report cannot
// beacon out to an attacker by referencing a remote image.
@(private)
CSP :: "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"

// STYLE is the entire presentation. Inline because a remote or separate
// stylesheet would violate the no-remote-resources rule and make the artifact
// non-self-contained.
@(private)
STYLE :: `
:root { color-scheme: light dark; }
body {
  font: 14px/1.5 ui-sans-serif, system-ui, -apple-system, sans-serif;
  margin: 0 auto; padding: 2rem; max-width: 60rem;
}
h1 { font-size: 1.5rem; margin: 0 0 0.25rem; }
h2 { font-size: 1.1rem; margin: 2rem 0 0.5rem; padding-bottom: 0.25rem;
     border-bottom: 1px solid currentColor; }
.subtitle { opacity: 0.7; margin: 0 0 1rem; }
table { border-collapse: collapse; width: 100%; margin: 0.5rem 0; }
th, td { text-align: left; padding: 0.35rem 0.75rem 0.35rem 0; vertical-align: top; }
th { font-weight: 600; opacity: 0.7; font-size: 0.85rem; }
tr + tr td { border-top: 1px solid rgba(128,128,128,0.25); }
code, .mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.9em; }
.level { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em;
         padding: 0.1rem 0.4rem; border: 1px solid currentColor; border-radius: 0.2rem; }
.score { font-variant-numeric: tabular-nums; font-weight: 600; }
.rules { margin: 0.25rem 0 0 1rem; padding: 0; list-style: none; opacity: 0.85; }
.rules li { font-size: 0.9em; }
.rules code { opacity: 0.8; }
.note { border-left: 3px solid currentColor; padding: 0.4rem 0 0.4rem 0.75rem;
        margin: 0.5rem 0; opacity: 0.85; }
.gap { font-size: 0.8rem; opacity: 0.8; }
.empty { opacity: 0.6; font-style: italic; }
.manifest li { margin: 0.15rem 0; }
footer { margin-top: 3rem; font-size: 0.8rem; opacity: 0.6; }
`

// render_html writes the bundle as a self-contained report. The caller owns
// the result.
render_html :: proc(bundle: ^Bundle, allocator := context.allocator) -> string {
	builder := strings.builder_make(allocator)
	b := &builder

	strings.write_string(b, "<!doctype html>\n<html lang=\"en\">\n<head>\n")
	strings.write_string(b, "<meta charset=\"utf-8\">\n")
	strings.write_string(b, "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.sbprintf(b, "<meta http-equiv=\"Content-Security-Policy\" content=\"%s\">\n", CSP)
	// The report must not leak its existence or contents to a third party if
	// it is ever opened from a server rather than a file.
	strings.write_string(b, "<meta name=\"referrer\" content=\"no-referrer\">\n")
	strings.write_string(b, "<title>Norn session report</title>\n")
	strings.write_string(b, "<style>")
	strings.write_string(b, STYLE)
	strings.write_string(b, "</style>\n</head>\n<body>\n")

	write_header_section(b, bundle)
	write_focus_section(b, bundle)
	write_candidates_section(b, bundle)
	write_outcomes_section(b, bundle)
	write_changes_section(b, bundle)
	write_timeline_section(b, bundle)
	write_manifest_section(b, bundle)

	strings.write_string(b, "<footer>Generated by Norn. Scores rank candidates; ")
	strings.write_string(b, "they are not probabilities and do not establish causation.</footer>\n")
	strings.write_string(b, "</body>\n</html>\n")

	return strings.to_string(builder)
}

@(private)
write_header_section :: proc(b: ^strings.Builder, bundle: ^Bundle) {
	strings.write_string(b, "<h1>Norn session report</h1>\n<p class=\"subtitle\">")
	escape_html(b, bundle.repository_name)
	strings.write_string(b, " &middot; imported by ")
	escape_html(b, bundle.importer_id)
	strings.write_byte(b, ' ')
	escape_html(b, bundle.importer_version)
	fmt.sbprintf(
		b,
		" &middot; sequences %d&ndash;%d</p>\n",
		u64(bundle.range_from),
		u64(bundle.range_to),
	)
}

@(private)
write_focus_section :: proc(b: ^strings.Builder, bundle: ^Bundle) {
	if !bundle.has_focus_outcome {
		return
	}

	strings.write_string(b, "<h2>Investigated outcome</h2>\n")

	// Find the focused outcome's own row for its description.
	for outcome in bundle.outcomes {
		if outcome.event != bundle.focus_outcome {
			continue
		}
		strings.write_string(b, "<p><span class=\"mono\">event ")
		fmt.sbprintf(b, "%d", u64(outcome.event))
		strings.write_string(b, "</span> &middot; ")
		escape_html(b, outcome.kind)
		strings.write_byte(b, ' ')
		escape_html(b, outcome.status)
		if outcome.subject != "" {
			strings.write_string(b, " &middot; ")
			escape_html(b, outcome.subject)
		}
		strings.write_string(b, "</p>\n")
		break
	}

	strings.write_string(b, "<p class=\"gap\">")
	if bundle.has_window_anchor {
		fmt.sbprintf(
			b,
			"Comparison window begins after the last comparable passing outcome (event %d).",
			u64(bundle.window_anchor),
		)
	} else {
		strings.write_string(
			b,
			"No comparable passing outcome precedes this failure, so the window begins at the containing phase or session start.",
		)
	}
	strings.write_string(b, "</p>\n")

	for note in bundle.uncertainties {
		strings.write_string(b, "<p class=\"note\">")
		escape_html(b, note)
		strings.write_string(b, "</p>\n")
	}
}

@(private)
write_candidates_section :: proc(b: ^strings.Builder, bundle: ^Bundle) {
	if !bundle.has_focus_outcome {
		return
	}

	// The heading states what these are. docs/01 requires the interface to say
	// "candidate contributor" unless an explicit relationship licenses more.
	strings.write_string(b, "<h2>Candidate contributors</h2>\n")

	if len(bundle.candidates) == 0 {
		strings.write_string(
			b,
			"<p class=\"empty\">No change in the window carries evidence linking it to this outcome.</p>\n",
		)
		return
	}

	strings.write_string(b, "<table>\n<tr><th>Score</th><th>Change</th><th>Evidence</th></tr>\n")
	for candidate in bundle.candidates {
		strings.write_string(b, "<tr><td class=\"score\">")
		fmt.sbprintf(b, "%.2f", f64(candidate.score))
		strings.write_string(b, "</td><td><span class=\"mono\">event ")
		fmt.sbprintf(b, "%d", u64(candidate.mutation_event))
		strings.write_string(b, "</span><br>")
		escape_html(b, candidate.path)
		if candidate.gap_capped {
			strings.write_string(
				b,
				"<br><span class=\"gap\">confidence capped: a replay gap affects this content</span>",
			)
		}
		strings.write_string(b, "</td><td><ul class=\"rules\">")
		for rule in candidate.rules {
			strings.write_string(b, "<li><code>")
			escape_html(b, rule.id)
			strings.write_string(b, "</code> ")
			escape_html(b, rule.reason)
			strings.write_string(b, "</li>")
		}
		strings.write_string(b, "</ul></td></tr>\n")
	}
	strings.write_string(b, "</table>\n")
}

@(private)
write_outcomes_section :: proc(b: ^strings.Builder, bundle: ^Bundle) {
	strings.write_string(b, "<h2>Outcomes in range</h2>\n")
	if len(bundle.outcomes) == 0 {
		strings.write_string(b, "<p class=\"empty\">No outcomes in the selected range.</p>\n")
		return
	}

	strings.write_string(b, "<table>\n<tr><th>Event</th><th>Kind</th><th>Status</th><th>Subject</th></tr>\n")
	for outcome in bundle.outcomes {
		strings.write_string(b, "<tr><td class=\"mono\">")
		fmt.sbprintf(b, "%d", u64(outcome.event))
		strings.write_string(b, "</td><td>")
		escape_html(b, outcome.kind)
		strings.write_string(b, "</td><td>")
		escape_html(b, outcome.status)
		strings.write_string(b, "</td><td>")
		escape_html(b, outcome.subject)
		strings.write_string(b, "</td></tr>\n")
	}
	strings.write_string(b, "</table>\n")
}

@(private)
write_changes_section :: proc(b: ^strings.Builder, bundle: ^Bundle) {
	strings.write_string(b, "<h2>Files changed</h2>\n")
	if len(bundle.changes) == 0 {
		strings.write_string(b, "<p class=\"empty\">No file changes in the selected range.</p>\n")
		return
	}

	strings.write_string(b, "<table>\n<tr><th>Path</th><th>Change</th><th></th></tr>\n")
	for change in bundle.changes {
		strings.write_string(b, "<tr><td class=\"mono\">")
		escape_html(b, change.path)
		strings.write_string(b, "</td><td>")
		escape_html(b, change.kind)
		strings.write_string(b, "</td><td class=\"gap\">")
		if change.affected_by_gap {
			// A diff resting on unreconstructable content is not a complete
			// diff, and docs/01 forbids presenting partial replay as complete.
			strings.write_string(b, "replay gap: content could not be reconstructed")
		}
		strings.write_string(b, "</td></tr>\n")
	}
	strings.write_string(b, "</table>\n")
}

@(private)
write_timeline_section :: proc(b: ^strings.Builder, bundle: ^Bundle) {
	strings.write_string(b, "<h2>Timeline</h2>\n")
	if len(bundle.events) == 0 {
		strings.write_string(b, "<p class=\"empty\">No events in the selected range.</p>\n")
		return
	}

	strings.write_string(b, "<table>\n<tr><th>Seq</th><th>Event</th><th>Kind</th><th>Detail</th></tr>\n")
	for event in bundle.events {
		strings.write_string(b, "<tr><td class=\"mono\">")
		fmt.sbprintf(b, "%d", u64(event.sequence))
		strings.write_string(b, "</td><td class=\"mono\">")
		fmt.sbprintf(b, "%d", u64(event.id))
		strings.write_string(b, "</td><td>")
		escape_html(b, fmt.tprintf("%v", event.kind))
		strings.write_string(b, "</td><td>")
		if event.path != "" {
			strings.write_string(b, "<span class=\"mono\">")
			escape_html(b, event.path)
			strings.write_string(b, "</span>")
			if event.summary != "" {
				strings.write_string(b, "<br>")
			}
		}
		escape_html(b, event.summary)
		strings.write_string(b, "</td></tr>\n")
	}
	strings.write_string(b, "</table>\n")
}

@(private)
write_manifest_section :: proc(b: ^strings.Builder, bundle: ^Bundle) {
	manifest := &bundle.manifest

	// docs/08 requires the inclusion manifest to be visible. Embedding it in
	// the artifact means a recipient can audit what they were sent without
	// reading every record.
	strings.write_string(b, "<h2>Contents of this export</h2>\n<ul class=\"manifest\">\n")
	write_manifest_line(b, "Prompt and response text", manifest.has_prompt_text)
	write_manifest_line(b, "File paths", manifest.has_file_paths)
	write_manifest_line(b, "Diffs", manifest.has_diffs)
	write_manifest_line(b, "Command lines", manifest.has_command_lines)
	write_manifest_line(b, "Command output", manifest.has_command_output)
	write_manifest_line(b, "Repository metadata", manifest.has_repository_metadata)
	write_manifest_line(b, "Raw provider records", manifest.has_raw_records)
	write_manifest_line(b, "Annotations", manifest.has_annotations)
	strings.write_string(b, "</ul>\n")

	if manifest.truncated_values > 0 {
		strings.write_string(b, "<p class=\"note\">")
		fmt.sbprintf(
			b,
			"%d value(s) were shortened to keep this report bounded and are marked incomplete.",
			manifest.truncated_values,
		)
		strings.write_string(b, "</p>\n")
	}

	// Redactions applied at import, by rule class and count. docs/08: reports
	// list rule identifiers and counts, never matched values.
	total_redactions := 0
	for count in manifest.redactions_by_category {
		total_redactions += int(count)
	}
	if total_redactions > 0 {
		strings.write_string(b, "<h2>Redactions applied at import</h2>\n<table>\n")
		strings.write_string(b, "<tr><th>Rule class</th><th>Count</th></tr>\n")
		for category in codec.Redaction_Category {
			count := manifest.redactions_by_category[int(category)]
			if count == 0 {
				continue
			}
			strings.write_string(b, "<tr><td>")
			escape_html(b, codec.redaction_category_name(category))
			strings.write_string(b, "</td><td>")
			fmt.sbprintf(b, "%d", count)
			strings.write_string(b, "</td></tr>\n")
		}
		strings.write_string(b, "</table>\n")
	}

	total_warnings := 0
	for count in manifest.warnings_by_category {
		total_warnings += int(count)
	}
	if total_warnings > 0 {
		// docs/01: import warnings remain part of the session metadata and do
		// not disappear, so they travel into the export too.
		strings.write_string(b, "<h2>Import warnings</h2>\n<table>\n")
		strings.write_string(b, "<tr><th>Category</th><th>Count</th></tr>\n")
		for category in codec.Warning_Category {
			count := manifest.warnings_by_category[int(category)]
			if count == 0 {
				continue
			}
			strings.write_string(b, "<tr><td>")
			escape_html(b, codec.warning_category_name(category))
			strings.write_string(b, "</td><td>")
			fmt.sbprintf(b, "%d", count)
			strings.write_string(b, "</td></tr>\n")
		}
		strings.write_string(b, "</table>\n")
	}
}

@(private)
write_manifest_line :: proc(b: ^strings.Builder, label: string, included: bool) {
	strings.write_string(b, "<li>")
	strings.write_string(b, "included" if included else "excluded")
	strings.write_string(b, " &mdash; ")
	escape_html(b, label)
	strings.write_string(b, "</li>\n")
}
